version: 0.2

phases:
  build:
    commands:
      - echo Entrando a fase de construccion
      - mvn clean package
  post_build:
    commands:
      - echo Construccion realizada correctamente
artifacts:
  files:
    - target/gamificacion-juego3d.jar
  discard-paths: yes